[package]
name = "crsh"
description = "Crappy Rust SHell. Basic implementation of a unix shell written in Rust, not meant to actually be used or taken seriously."
version = "0.0.1"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/ndunnett/crsh"
repository = "https://github.com/ndunnett/crsh"
license-file = "LICENSE"
categories = ["command-line-utilities"]
keywords = ["shell", "unix"]

[dependencies]
crossterm = "0.27"
strip-ansi-escapes = "0.2.0"
logos = "0.14.0"
os_pipe = "1.2.0"
